#!/bin/bash
#Docker
#docker run -p 80:80 -ti debian /bin/bash
#Dependencias
apt-get update
apt-get install wget sudo nano postgresql locales-all -y
#a. Instale o repositório Zabbix
wget https://repo.zabbix.com/zabbix/5.2/debian/pool/main/z/zabbix-release/zabbix-release_5.2-1+debian10_all.deb
dpkg -i zabbix-release_5.2-1+debian10_all.deb
apt update
#b. Instale o servidor, o frontend e o agente Zabbix
apt install -y zabbix-server-pgsql zabbix-frontend-php php7.3-pgsql zabbix-apache-conf zabbix-agent
#c. Criar banco de dados inicial
/etc/init.d/postgresql start
#sudo -u postgres createuser --pwprompt zabbix
@sudo -u postgres createuser zabbix
sudo -u postgres psql -c "create role zabbix with login password '123456';"
sudo -u postgres createdb -O zabbix zabbix
zcat /usr/share/doc/zabbix-server-pgsql*/create.sql.gz | sudo -u zabbix psql zabbix
sed -i 's/# DBPassword=/DBPassword=123456/g' /etc/zabbix/zabbix_server.conf
#Reiniciando serviços
/etc/init.d/zabbix-agent restart
/etc/init.d/zabbix-server restart
/etc/init.d/apache2 restart
